import React from "react";
import Head from "next/head";

// External Components
import { Section, Box } from "@thepuzzlers/pieces";
import { NavigationBar } from "@/components/NavigationBar";
import { CartPreview } from "@/components/CartPreview";

import Link from "next/link";
import TranslatedLink from "@/components/TranslatedLink";
import { LanguageSwitchLinkGroup } from "@/components/LanguageSwitchLinkGroup";

export default function Home({}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavigationBar />
      <Section as="main">
        {/* content goes here */}

        <Box
          sx={{
            gridColumn: "1/ span 10",
            display: "flex",
            alignSelf: "start",
            gap: "2rem",
            my: "3rem",
          }}
        >
          <TranslatedLink
            href="/blog"
            sx={{
              variant: "buttons.secondary",
            }}
          >
            Go to BLOG
          </TranslatedLink>
          <Link href="/blog" sx={{}}>
            Default Next Link to Blog
          </Link>

          <LanguageSwitchLinkGroup />
          <TranslatedLink
            href="/legal-page"
            sx={{
              variant: "buttons.secondary",
            }}
          >
            Go To Legal Page
          </TranslatedLink>
        </Box>
      </Section>
    </>
  );
}

export async function getServerSideProps({ locales, locale }) {
  // A Storefront API query, defined in a separate file where you make queries.
  //? language setting refer to https://shopify.dev/docs/api/storefront#directives

  return { props: {} };
}
