import React from "react";
import Head from "next/head";
import { LegalPages, LegalPagesDe } from "@/components/library";
import { useRouter } from "next/router";
import { LanguageSwitchLinkGroup } from "@/components/LanguageSwitchLinkGroup";
import TranslatedLink from "@/components/TranslatedLink";

export default function Legal() {
  const { locale } = useRouter();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {locale === "de" ? <LegalPagesDe /> : <LegalPages />}
      <LanguageSwitchLinkGroup />
      <TranslatedLink
        href="/"
        sx={{
          variant: "buttons.secondary",
          mt: "4rem",
          display: "inline-block",
        }}
      >
        Back to Home
      </TranslatedLink>
    </>
  );
}
